# Generated by Django 3.0.5 on 2020-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
