# Generated by Django 3.0.5 on 2020-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200610_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_email', models.CharField(max_length=50)),
                ('c_phone', models.CharField(max_length=12)),
                ('c_query', models.CharField(max_length=500)),
            ],
        ),
    ]
