# Generated by Django 3.0.5 on 2020-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('o_name', models.CharField(max_length=100)),
                ('o_email', models.CharField(max_length=50)),
                ('o_address', models.CharField(max_length=500)),
                ('o_city', models.CharField(max_length=50)),
                ('o_state', models.CharField(max_length=50)),
                ('o_zip', models.CharField(max_length=10)),
                ('o_phone', models.CharField(max_length=12)),
            ],
        ),
    ]
