# Generated by Django 3.0.5 on 2020-09-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
